### ISSUE TITLE
Use OpenAsBlob

### ISSUE THREAD

**Issue by jimmywarting** [BugSplat-Git/node-streamable-file#2]
Should actually be using `fs.openAsBlob(path, { type })` instead.

also, fyi you don't need a `File` in order to use it with FormData.
Just do `fd.set('field', blob, filename)`

there is no real need to create a `File` but if you want a file you could do: `new File([blob], filename)`

**Comment by bobbyg603** [comment]
Hi @jimmywarting, fs.openAsBlob appears to have been added in 19.8. Perhaps we should have been more specific, but we're using this as a workaround for a pkg issue, and pkg only supports 18.5 (we're also using a File polyfill in an unreleased version of this library). We are unaware of a streaming blob implementation in 18.5. Are you aware of a solution that meets these constraints?

**Comment by jimmywarting** [comment]
> We are unaware of a streaming blob implementation in 18.5. Are you aware of a solution that meets these constraints?

Do you mean that your blob/file polyfill (@web-std/file) dose not meet the criteria to be used in `FormData`?

I have built a Blob/File polyfill myself (fetch-blob) that works with undici's fetch + formData

**Comment by bobbyg603** [comment]
> > We are unaware of a streaming blob implementation in 18.5. Are you aware of a solution that meets these constraints?
> 
> Do you mean that your blob/file polyfill (@web-std/file) dose not meet the criteria to be used in `FormData`?
> 
> I have built a Blob/File polyfill myself (fetch-blob) that works with undici's fetch + formData

I wasn't aware that fetch-blob existed, thanks for sharing
